// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBcq8YB5KNg47lIjGPmDOeh0Ipbx4W-Y',
    appId: '1:721417010542:web:0b3d77926d8e3a24b7d57f',
    messagingSenderId: '721417010542',
    projectId: 'chat-box-1b56e',
    authDomain: 'chat-box-1b56e.firebaseapp.com',
    storageBucket: 'chat-box-1b56e.appspot.com',
    measurementId: 'G-BQSQMESSJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLv8IKxjrf4LJ3Elx5TBOMTPxPs5qE5Bc',
    appId: '1:721417010542:android:750d0755fb0ddaf5b7d57f',
    messagingSenderId: '721417010542',
    projectId: 'chat-box-1b56e',
    storageBucket: 'chat-box-1b56e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pbz3M65ZL_0Po3EdmT2B4ot_N8hKgPk',
    appId: '1:721417010542:ios:b5786a0b32ee09f4b7d57f',
    messagingSenderId: '721417010542',
    projectId: 'chat-box-1b56e',
    storageBucket: 'chat-box-1b56e.appspot.com',
    androidClientId: '721417010542-u6ak8bm6a8dvp6gvp24bnv8fsc0u19ao.apps.googleusercontent.com',
    iosClientId: '721417010542-4v63k18s51vraqr809slh23kcnftunjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8pbz3M65ZL_0Po3EdmT2B4ot_N8hKgPk',
    appId: '1:721417010542:ios:4fd0deb9d3b163acb7d57f',
    messagingSenderId: '721417010542',
    projectId: 'chat-box-1b56e',
    storageBucket: 'chat-box-1b56e.appspot.com',
    androidClientId: '721417010542-u6ak8bm6a8dvp6gvp24bnv8fsc0u19ao.apps.googleusercontent.com',
    iosClientId: '721417010542-kmnvlsf8rhggm86q0q6vn2iemt8q6u0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatBox.RunnerTests',
  );
}
